In [3]:
import numpy as np
wines = np.genfromtxt("winequality-red.csv", delimiter=";", skip_header=1)

In [4]:
wines.shape

(1599, 12)

In [5]:
wines.shape[0]

1599

In [6]:
wines.shape[1]

12

In [7]:
wines.ndim

2

In [8]:
 type(wines)

numpy.ndarray

In [9]:
wines.dtype

dtype('float64')

In [10]:
 wines[2,3]

2.3

In [11]:
wines[:3, 3]

array([1.9, 2.6, 2.3])

In [12]:
 wines[:, 0]

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])

In [13]:
wines[1, :]

array([ 7.8   ,  0.88  ,  0.    ,  2.6   ,  0.098 , 25.    , 67.    ,
        0.9968,  3.2   ,  0.68  ,  9.8   ,     nan])

In [14]:
wines[1:4, 4]

array([0.098, 0.092, 0.075])

In [15]:
wines[:,:]

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,    nan],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,    nan],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,    nan],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,    nan],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,    nan],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,    nan]])

In [16]:
wines[0,0]

7.4

In [17]:
wines[0,0] = 100

In [18]:
wines[0,0]

100.0

In [20]:
wines[0,0] = 7.4

In [28]:
third_wine = wines[3, :]

In [29]:
third_wine

array([11.2  ,  0.28 ,  0.56 ,  1.9  ,  0.075, 17.   , 60.   ,  0.998,
        3.16 ,  0.58 ,  9.8  ,    nan])

In [30]:
third_wine[1]

0.28

In [31]:
wines.astype(int)

array([[          7,           0,           0, ...,           0,
                  9, -2147483648],
       [          7,           0,           0, ...,           0,
                  9, -2147483648],
       [          7,           0,           0, ...,           0,
                  9, -2147483648],
       ...,
       [          6,           0,           0, ...,           0,
                 11, -2147483648],
       [          5,           0,           0, ...,           0,
                 10, -2147483648],
       [          6,           0,           0, ...,           0,
                 11, -2147483648]])

In [32]:
wines[:, 11]

array([nan, nan, nan, ..., nan, nan, nan])

In [33]:
wines[:, 11] += 10

In [34]:
wines[:, 11]

array([nan, nan, nan, ..., nan, nan, nan])

In [35]:
 wines[:, 10] *= 3

In [36]:
wines[:, 10]

array([28.2, 29.4, 29.4, ..., 33. , 30.6, 33. ])

In [37]:
wines[:, 11] + wines[:, 11]

array([nan, nan, nan, ..., nan, nan, nan])

In [39]:
wines[:,10] * wines[:,11]

array([nan, nan, nan, ..., nan, nan, nan])

In [47]:
 rand_array = np.random.rand(12) 

In [48]:
rand_array

array([0.80253175, 0.92756494, 0.80045798, 0.74620715, 0.55075698,
       0.6980907 , 0.35418985, 0.71244404, 0.12625357, 0.09026317,
       0.01108523, 0.8868359 ])

In [49]:
wines + rand_array

array([[ 8.20253175,  1.62756494,  0.80045798, ...,  0.65026317,
        28.21108523,         nan],
       [ 8.60253175,  1.80756494,  0.80045798, ...,  0.77026317,
        29.41108523,         nan],
       [ 8.60253175,  1.68756494,  0.84045798, ...,  0.74026317,
        29.41108523,         nan],
       ...,
       [ 7.10253175,  1.43756494,  0.93045798, ...,  0.84026317,
        33.01108523,         nan],
       [ 6.70253175,  1.57256494,  0.92045798, ...,  0.80026317,
        30.61108523,         nan],
       [ 6.80253175,  1.23756494,  1.27045798, ...,  0.75026317,
        33.01108523,         nan]])